version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/rocket
      - ./rocket.template:/etc/nginx/conf.d/rocket.template
    links:
      - php
    command: /bin/bash -c "cp -f /etc/nginx/conf.d/rocket.template /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  php:
    image: php:5.6-fpm
    volumes:
      - .:/var/www/rocket
